### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'encoding'

### ISSUE THREAD

**Issue by 18382374375** [Wesly-Yu/AutoZone#2]
点击立即执行web ui自动化脚本时，提示编码错误。报错信息如下
self.encoding = charset_by_name(self.charset).encoding
AttributeError: 'NoneType' object has no attribute 'encoding'

**Comment by Wesly-Yu** [comment]
正确的写法应该是这样的coon = pymysql.connect(user='root', password='test123456', db='autotest', port=3306, host='127.0.0.1‘， charset='utf8')
charset="utf-8"这样写造成的报错
