### ISSUE TITLE
webUItest调用SikuliLibrary库，报java错误

### ISSUE THREAD

**Issue by Dogeballer** [Wesly-Yu/AutoZone#4]
webUItest调用SikuliLibrary库的时候，报20190605 06:49:04.793 :  FAIL : java.lang.ExceptionInInitializerError: null错误，无法识别指定文件图像

**Comment by Wesly-Yu** [comment]
将sikulilibrary的安装版本改为1.13 便可以解决问题

**Comment by Wesly-Yu** [comment]
sorry version is:1.03
